services:
  db:
    image: postgres:15.3-bookworm
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    networks:
      internal:
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
    name: "character-builder-api-postgres-data"
